name: Unit tests

on:
  pull_request:

jobs:
  tests:
    name: "Unit tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@2.7.0
        with:
          coverage: "none"
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - run: composer install

      - name: Run tests
        run: vendor/bin/phpunit -c phpunit.xml.dist --colors=always
